ktor:
  application:
    modules:
      - com.github.radlance.com.github.radlance.autodispatch.ApplicationKt.module
  deployment:
    port: 8084
database:
  driver: org.postgresql.Driver
  url: ${DB_URL}
  user: postgres
  password: 1