services:
  api:
    container_name: auto_dispatch_api
    build: .
    expose:
      - "8084"
    ports:
      - "8084:8084"
    volumes:
      - uploaded_files:/uploads
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/auto_dispatch_api
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=AutoDispatchApi
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none

  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    networks:
      default:
        aliases:
          - otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  nginx:
    container_name: auto_dispatch_nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploaded_files:/uploads:ro
    depends_on:
      - api

  db:
    container_name: postgres_db
    image: postgres:18
    volumes:
      - tmp_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: auto_dispatch_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq_broker
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  uploaded_files:
  tmp_db:
  rabbit_data:
