services:
  api:
    container_name: auto_dispatch_api
    build: .
    expose:
      - "8084"
    ports:
      - "8084:8084"
    volumes:
      - uploaded_files:/uploads
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/auto_dispatch_api
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      MODE: release
      OTEL_RESOURCE_ATTRIBUTES: "service.name=AutoDispatchApi,service.instance.id=AutoDispatchApi"
      OTEL_SERVICE_NAME: AutoDispatchApi
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1@db:5432/auto_dispatch_api?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "3570:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - api
      - postgres_exporter
      - rabbitmq

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: "104"
    volumes:
      - ./observability/grafana:/etc/grafana/provisioning
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    links:
      - api
      - prometheus

  nginx:
    container_name: auto_dispatch_nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploaded_files:/uploads:ro
    depends_on:
      - api

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - '--nginx.scrape-uri=http://nginx/stub_status'
    depends_on:
      - nginx

  db:
    container_name: postgres_db
    image: postgres:18
    volumes:
      - tmp_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: auto_dispatch_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq_broker
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./observability/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  uploaded_files:
  tmp_db:
  rabbit_data:
  lgtm_data:
