events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        client_max_body_size 20M;

        location /static/ {
            alias /uploads/;
        }

        location / {
            proxy_pass http://host.docker.internal:8084;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
