scrape_configs:
  - job_name: 'AutoDispatchApi'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8084']

  - job_name: 'postgresql'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'rabbitmq'
    scrape_interval: 15s
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginx_exporter:9113']