CREATE TABLE maintenance
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id         INT         NOT NULL REFERENCES vehicle (id) ON DELETE CASCADE,
    service_date       DATE        NOT NULL,
    mileage_at_service INT CHECK (mileage_at_service >= 0),
    service_type       VARCHAR(50) NOT NULL,
    description        TEXT,
    cost               DECIMAL(10, 2) CHECK (cost >= 0),
    next_service_date  DATE
);