CREATE TABLE fuel_records
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id     INT           NOT NULL REFERENCES vehicle (id) ON DELETE CASCADE,
    driver_id      INT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    request_id     INT           REFERENCES request (id) ON DELETE SET NULL,
    refuel_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    liters         DECIMAL(8, 2) NOT NULL CHECK (liters > 0),
    cost_per_liter DECIMAL(8, 2) CHECK (cost_per_liter >= 0),
    total_cost     DECIMAL(10, 2) GENERATED ALWAYS AS (liters * cost_per_liter) STORED,
    receipt_photo  VARCHAR(255)
);
