CREATE TABLE request_status
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(50)        NOT NULL CHECK (name IN ('Новая', 'Назначена', 'В пути', 'Завершена', 'Отменена'))
);
