CREATE TABLE vehicle
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model             VARCHAR(100)       NOT NULL,
    license_plate     VARCHAR(20) UNIQUE NOT NULL,
    year              SMALLINT CHECK (year BETWEEN 1980 AND EXTRACT(YEAR FROM CURRENT_DATE)),
    mileage           INT                NOT NULL DEFAULT 0 CHECK (mileage >= 0),
    fuel_type         VARCHAR(20)        NOT NULL CHECK (fuel_type IN ('Бензин', 'Дизель', 'Электро')),
    status_id         INT REFERENCES vehicle_status (id),
    last_service_date DATE,
    is_active         BOOLEAN            NOT NULL DEFAULT TRUE
);