CREATE TABLE driver_shift
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id   INT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time  TIME     NOT NULL,
    end_time    TIME     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_driver_shift UNIQUE (driver_id, day_of_week, start_time, end_time),
    CONSTRAINT ck_driver_shift_time CHECK (start_time <> end_time)
);

CREATE INDEX idx_driver_shift_driver_day ON driver_shift (driver_id, day_of_week);
