CREATE TABLE request
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_id INT          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    route_id      INT          REFERENCES route (id) ON DELETE SET NULL,
    status_id     INT          NOT NULL REFERENCES request_status (id) ON DELETE RESTRICT,
    origin        VARCHAR(255) NOT NULL,
    destination   VARCHAR(255) NOT NULL,
    purpose       VARCHAR(150) NOT NULL,
    trip_date     DATE         NOT NULL,
    started_trip_at    TIMESTAMP,
    ended_trip_at      TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);