CREATE TABLE request
(
    id                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_id              INT               NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status_id                  INT               NOT NULL REFERENCES request_status (id) ON DELETE RESTRICT,
    origin_id                  INT REFERENCES city (id),
    destination_id             INT REFERENCES city (id),
    loading_point              VARCHAR(255)      NOT NULL,
    unloading_point            VARCHAR(255)      NOT NULL,
    cargo_type_id              INT REFERENCES cargo_type (id),
    cargo_weight               FLOAT             NOT NULL,
    cargo_volume               FLOAT,
    cargo_description          TEXT,
    customer_id                INT REFERENCES customer (id),
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    request_number             VARCHAR(6) UNIQUE NOT NULL,
    transportation_description TEXT
);