CREATE TABLE users
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100)        NOT NULL,
    login         VARCHAR(50) UNIQUE  NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255)        NOT NULL,
    salt          VARCHAR(255)        NOT NULL,
    avatar_url    VARCHAR(512),
    phone_number  VARCHAR(20),
    role_id       INT REFERENCES role (id),
    status_id     INT REFERENCES user_status (id) DEFAULT 1,
    created_by    INT                 NULL REFERENCES users (id),
    updated_by    INT                 NULL REFERENCES users (id),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE,
    last_login_at TIMESTAMP WITH TIME ZONE
);  