CREATE TABLE delivery_document
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id INT REFERENCES assignment (id) ON DELETE CASCADE,
    image_url     VARCHAR(255) NOT NULL,
    type_id       INT REFERENCES delivery_document_type (id) ON DELETE CASCADE,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);