CREATE TABLE notification
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      VARCHAR(100) NOT NULL,
    message    TEXT         NOT NULL,
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE
);