CREATE TABLE trip_report
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    INT NOT NULL UNIQUE REFERENCES request (id) ON DELETE CASCADE,
    driver_id     INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    start_mileage INT NOT NULL CHECK (start_mileage >= 0),
    end_mileage   INT NOT NULL CHECK (end_mileage >= start_mileage),
    fuel_used     DECIMAL(8, 2) CHECK (fuel_used >= 0),
    comment       TEXT,
    photo_report  VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);