CREATE TABLE vehicle
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model            VARCHAR(100)       NOT NULL,
    license_plate    VARCHAR(20) UNIQUE NOT NULL,
    payload_capacity INT                NOT NULL CHECK (payload_capacity >= 0)
);